### ISSUE TITLE
Origin of MQTT credentials unknown

### ISSUE THREAD

**Issue by makuser** [h-mdm/hmdm-android#15]
Version 5.18 is having problems connecting to the integrated MQTT server.
Debugging the connection showed the used password is unknown. I do not know where the used value would come from, especially not from looking at the code.

log
```
org.apache.activemq.broker.TransportConnection : Failed to add Connection id=ID:server-42919-1684767127952-3:23, clientId=IMEI due to java.lang.SecurityException: User name [hmdm] or password is invalid.
org.apache.activemq.broker.TransportConnection.Service : Security Error occurred on connection to: tcp://1.2.3.4:47292, User name [hmdm] or password is invalid.
org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://1.2.3.4:47292 failed: java.io.IOException: User name [hmdm] or password is invalid.
org.apache.activemq.broker.TransportConnection : Stopping tcp://1.2.3.4:47292 because Failed with SecurityException: User name [hmdm] or password is invalid.
```

The used password has 40 chars, starting with E151DB...

**Comment by h-mdm** [comment]
The MQTT password set by the mobile agent is: SHA1("hmdm" + BuildConfig.REQUEST_SIGNATURE). In version 5.18, the request signature has changed, so you need to adjust the parameter hash.secret in the XML config (/var/lib/tomcat9/conf/Catalina/localhost/ROOT.xml). Please contact https://h-mdm.com/contact-us/ to inquiry for the up-to-date shared secret.
