### ISSUE TITLE
Kiosk mode

### ISSUE THREAD

**Issue by Liscanoj** [h-mdm/hmdm-android#16]
Me pueden proporcionar una guía de como funciona y que hace ese modo?

**Comment by h-mdm** [comment]
Kiosk mode is not available in the free version, sorry about that. You can read more about the kiosk mode here: https://h-mdm.com/kiosk-mode/  To get a free trial of Headwind MDM Premium which can work in kiosk mode, please submit the contact form on the Headwind MDM website.

**Comment by Liscanoj** [comment]
De acuerdo gracias
