### ISSUE TITLE
What if the device does NOT have an internal QR code scanner?

### ISSUE THREAD

**Issue by tgarm** [h-mdm/hmdm-android#20]
When dealing with Android Kiosk (without GMS) that does not have a internal QR code scanner, the ordinary enrollment method does not work.
Is there any other way to enroll these devices into MDM, for instance, with 'adb'?

**Comment by h-mdm** [comment]
Yes, there is. See details here: https://qa.h-mdm.com/16619/how-to-install-headwind-mdm-mobile-app-without-code-scanning

**Comment by tgarm** [comment]
Thank you. It's very helpful.
