### ISSUE TITLE
Hard Reset Stop

### ISSUE THREAD

**Issue by safalbhatia** [h-mdm/hmdm-android#22]
Is this possible User cannot hard reset device? 
or
When User hard reset his device then Without enter email and password user not setup device.

**Comment by h-mdm** [comment]
Headwind MDM cannot prevent the hard reset. There is a factory reset protection provided by Google, you can turn it on manually by registering a Google account on a device. Headwind MDM is not integrated with Google so it can't turn on factory reset protection.
