### ISSUE TITLE
No silent app install

### ISSUE THREAD

**Issue by Tualua** [h-mdm/hmdm-android#23]
Hello!

I'm trying to use H-MDM with Urovo DT40 device. Devices we have does not have Google services in firmware, so there is no setup wizard. I installed launcher manually and everything worked fine except that every app installation requires user confirmation. 
Is there any way to fix it?

**Comment by h-mdm** [comment]
Silent app installation requires elevated (Device Owner or System) permissions. Please review available options here: https://qa.h-mdm.com/1893/silent-installation-of-apk-without-qr-code-enrollment   I think in your case only ADB option would work.
