### ISSUE TITLE
package conflict issue

### ISSUE THREAD

**Issue by jatin141141** [h-mdm/hmdm-android#25]
Hello Suppprt team,
![Screenshot 2024-02-22 at 12 48 55 PM](https://github.com/h-mdm/hmdm-android/assets/133774011/5dfb084f-3c3a-4a4b-a468-3ea7f72fcb06)

i have checked the demo but unable to control device using  web portal
https://app.h-mdm.com/#/login

i have try camera lock but it is not working in application side.

when i am update app getting the alert conflict package please check screen shot

**Comment by h-mdm** [comment]
When you build Headwind MDM from the source code, you sign it with your own keys whereas the prebuilt APK is signed with Headwind MDM's keys. You cannot update a package if you use different keys.

To fix the issue, uninstall the existing Headwind MDM APK (or reset the device to factory defaults if you set it as a Device Owner app), then install the compiled APK.

**Comment by jatin141141** [comment]
Hello Support Team,

i have used your code to then create apk but when i am update apk using headwind mdm server but same issue happen
