### ISSUE TITLE
MDM update/flow issue

### ISSUE THREAD

**Issue by Harsh-SA** [h-mdm/hmdm-android#26]
Hello,

We have complied your source code and run it on android device and In admin portal I have applied changes but those changes does not reflected on app side.

1) I want to block app and setting from outside MDM agent which flow do I need to follow?
2) Whatever changes is applied on admin portal how I check in app side does it automatically applies or do I need to be update MDM agent?
3) Not able to update MDM agent? due to conflicts with an existing packages?

**Comment by gainskills** [comment]
https://h-mdm.com/update/#launcher for reference

**Comment by h-mdm** [comment]
The issues section on github is for bug reports and feature requests. Please use our Q&A forum to find answers or ask questions about Headwind MDM operation: https://qa.h-mdm.com. Thank you for understanding.
