### ISSUE TITLE
Not able to create user profiles [Background (Agent) Mode] 

### ISSUE THREAD

**Issue by AafaaqAli** [h-mdm/hmdm-android#29]
Hello, I am using a custom ROM and headwind MDM, and whenever I try to create User profile when headwind MDM is added in the ROM  I just can't create a profile, **Add profile** button just does not show.. and if I remove the app then I can create and manage the user profiles.

I need some clarification on this one, any help is greatly appreciated 

Regards. 
A.

**Comment by h-mdm** [comment]
Headwind MDM doesn't forbid to create user profiles, unless you add the related restriction in the configuration details -> MDM Settings -> Restrictions (no_add_managed_profile, no_add_private_profile, or no_add_user). Please check this setting.

If you didn't add these restrictions, probably the OS itself forbids to create user profiles on a managed device. In this case, the only way to fix that is to dig into the Android source code and patch it to change this behavior.

**Comment by AafaaqAli** [comment]
Hi thank you for a quick response, upon the further discussion from android 14, if was have a device owner we cannot add profiles , so I was hoping if there is any other way with h-mdm to get this done ?
