### ISSUE TITLE
Android 14 Mqtt Service Connection Issue.

### ISSUE THREAD

**Issue by mfarhanmail** [h-mdm/hmdm-android#33]
I was testing launcher in android 14 device, MQTT connection was not getting established and dialog "Requesting for config file from server" was taking long time. After debugging alot i found that this is happening due to **"Changes to BroadcastReceiver in Android 14"**

```
Logs:
 MqttConnection Connecting {tcp://serverip} as {deviceId}
 MqttConnection Do Real connect!
 MqttConnection disconnect()
 disconnect not connected
 null not connected
```

After modifying **start()** method in **AlarmPingSender.java** it started working properly.  

```
if (Build.VERSION.SDK_INT > Build.VERSION_CODES.TIRAMISU) {
            service.registerReceiver(alarmReceiver, new IntentFilter(action), Context.RECEIVER_NOT_EXPORTED);
        } else {
            service.registerReceiver(alarmReceiver, new IntentFilter(action));
        }
```

> We can even use ContextCompact.registerReceiver(). My project is using  compileSdk 35 and targetSdk 34

Couldn't see this changes in repo, so thought of adding it here for any other users facing similar issue.

**Comment by h-mdm** [comment]
Thank you for your comment! For some reason, lint didn't show all places where a deprecated call of registerReceiver() has been done. We will fix all entries in the next release of Headwind MDM launcher.
