### ISSUE TITLE
Andorid 10 Bug: java.lang.NoSuchMethodException: android.telephony.TelephonyManager.getSubscriberId

### ISSUE THREAD

**Issue by Byteschmiede** [h-mdm/hmdm-android#4]
We are using HUAWEI MatePad T with MDM and those devices running on Android 10.

The problem is, that these devices can't send device info since the app uses illegal methods to get System Infos
![Bildschirmfoto 2022-01-12 um 08 42 21](https://user-images.githubusercontent.com/7261828/149085511-c9507e9d-eca8-4544-a6d7-064c820005a6.png)

Accessing hidden method Landroid/telephony/TelephonyManager;->getSubscriberId(I)Ljava/lang/String; (greylist-max-p, reflection, denied)

Reference: https://developer.android.com/about/versions/10/non-sdk-q

**Comment by h-mdm** [comment]
Looks like IMSI can't be determined on Android 10 and above, unless the MDM app is signed by platform keys: https://source.android.com/devices/tech/config/device-identifiers

This exception is caught and just logged, so it doesn't affect the application work.
